apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockerhost
  name: dockerhost
  namespace: remote-secrets
spec:
  externalName: host.docker.internal
  ports:
    - name: aws-mock
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: vault
      protocol: TCP
      port: 8200
      targetPort: 8200
  type: ExternalName
status:
  loadBalancer: {}
