apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockerhost
  name: dockerhost
  namespace: remote-secrets
spec:
  clusterIP: None
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: dockerhost-1
  namespace: remote-secrets
  labels:
    kubernetes.io/service-name: dockerhost
addressType: IPv4
endpoints:
  - addresses:
      - 172.17.0.1
ports:
  - name: http
    protocol: TCP
    port: 4566
