services:
  vault-server:
    image: vault:1.13.3
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
  floci:
    image: floci/floci:latest-compat
    ports:
      - "4566:4566"
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      FLOCI_INIT_HOOKS_TIMEOUT_SECONDS: "120"
    volumes:
      - ./floci/ready.d:/etc/floci/init/ready.d:ro
      - ./mock-cfn.yaml:/etc/floci/templates/mock-cfn.yaml:ro
