name: Rust Cache
on:
  schedule:
    - cron: "30 14 * * 0"
jobs:
  cache:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CARGO_INCREMENTAL: "0"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.93.1
          components: clippy, rustfmt

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: scheduled
          cache-on-failure: true

      - name: Build Cache
        run: |
          cargo build --workspace --all-features --all-targets
